version: "3.6"
services:
  app:
    container_name: app
    image: index.docker.io/matveizhukov/app
    command: python app.py
    volumes:
      - ./instance:/app/instance
    networks:
      - main
    ports:
      - "5000:5000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope app
networks:
  main:
    driver: bridge